driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096
  synced_folders:
    - ['.', '/home/vagrant/opennebula-vmcatcher-integration']

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.4.0

platforms:
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: centos-6.5
  - name: centos-7.1
    run_list: yum-epel::default
  - name: debian-7.6
    run_list: apt::default
  - name: debian-8.2
    run_list: apt::default

suites:
  - name: default
    run_list:
      - omnibus::default
      - omnibus-build::default
    attributes:
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/opennebula-vmcatcher-integration
        install_dir: /opt/opennebula-vmcatcher-integration
