#!/bin/bash
#
# Perform necessary one-integration-vmcatcher removal steps
# after package is uninstalled.
#

PROGNAME=`basename $0`
INSTALLER_DIR=`dirname $0`
DEST_DIR=/opt/one-integration-vmcatcher
BIN_DIR=/usr/bin
CRON_JOB=/etc/cron.d/one-integration-vmcatcher
INIT_SCRIPT=/etc/init.d/one-integration-vmcatcher-cron
USAGE="usage: $0"

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

if [ "X$1" = "Xupgrade" ] || [ "X$1" = "X1" ]; then
  echo "Skipping clean-up, this is an upgrade!"
  exit 0
fi

if [ -f ${CRON_JOB} ]; then
  rm ${CRON_JOB}
fi

if [ -f ${INIT_SCRIPT} ]; then
  rm ${INIT_SCRIPT}
fi

echo "one-integration-vmcatcher has been uninstalled!"

exit 0
