#!/bin/bash
#
# Perform necessary one-integration-vmcatcher setup steps
# prior to removing package.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

exit 0
