#!/bin/bash

source /etc/vmcatcher/vmcatcher-env

PROGNAME=${0##*/}
lockfile=/var/tmp/comfy_family.lock
vmcatcher_user=vmcatcher
vmcatcher_setup="vmcatcher_subscribe -U"
vmcatcher_command=vmcatcher_cache
nifty_user=nifty
nifty_command="nifty opennebula"
itchy_user=itchy
itchy_command="itchy process"

function clean_lock {
  rm -f "$lockfile"
}

function error_exit {
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  clean_lock
  exit 1
}

if ( set -o noclobber; echo "$$" > "$lockfile") 2> /dev/null; then

  trap clean_lock INT TERM EXIT

  error=$(su $vmcatcher_user -s /bin/bash -c "source /etc/vmcatcher/vmcatcher-env && $vmcatcher_setup")
  if [ $? -ne 0 ] ; then
    error_exit "$error"
  fi

  error=$(su $vmcatcher_user -s /bin/bash -c "source /etc/vmcatcher/vmcatcher-env && $vmcatcher_command")
  if [ $? -ne 0 ] ; then
    error_exit "$error"
  fi

  error=$(su $itchy_user -s /bin/bash -c "$itchy_command")
  if [ $? -ne 0 ] ; then
    echo "$error"
    error_exit "$error"
  fi
      
  error=$(su $nifty_user -s /bin/bash -c "$nifty_command")
  if [ $? -ne 0 ] ; then
    error_exit "$error"
  fi

  # clean up
  clean_lock
else
  echo "Lock Exists: $lockfile owned by $(cat $lockfile)"
fi
